<style>
.container a{
color:#217ED3;
}
.container a em{
color:#217ED3;
}
</style>
<section class="page-title-wrap">
  <div class="shell">
    <div class="page-title">
		<h2>Leopoldo Zea</h2>
</section>
<section class="section-sm-50">
	<div class="shell">
		<ol class="breadcrumb">
		  <li data-file="index" data-folder="inicio" class="load-content"><i class="fa fa-home" aria-hidden="true"></i></li>
		  <li data-process="true" data-file="quienes" data-folder="nosotros|cialcunam" class="load-content">¿Quiénes somos?</li>
		  <li class="active">Leopoldo Zea</li>
		</ol>
	</div>
</section>
  <section class="section-60 section-sm-top-90 section-sm-bottom-100">

      <div class="container">
        <div class="row">
          <div class="col-sm-12">

            <h4>LEOPOLDO ZEA (1912-2004)</h4>
                <img class="imgfloat" src="<?=URL_PUBLIC?>frontend/old/imgs/internas/investigadores/zeafotoch.jpg">
            		<p>Alberto SALADINO GARCÍA

                      <h5>DATOS BIOGRÁFICOS</h5>

                      <p>Leopoldo Zea es hijo de Leopoldo Zea y Luz Aguilar,nació el 30 de junio de 1912 en la ciudad de México, justamente en la primavera democrática del gobierno de Francisco I. Madero. La educación familiar corrió a cargo de su abuela Micaela Aguilar, quien respaldó su instrucción primaria en la escuela de los hermanos La Salle, donde obtuvo una beca para terminarla. En 1929 participó en la campaña presidencial de José Vasconcelos, donde conoció a otros jóvenes visionarios con los cuales se reencontraría después, como Adolfo López Mateos.</p>

                      <p>Para ayudar al sostenimiento de su casa, desde temprana edad, desempeñó diversos trabajos, en 1933 consiguió una plaza como mensajero en Telégrafos Nacionales, por lo que pudo continuar sus estudios, inscribiéndose en la Escuela Secundaria Nocturna, al terminar este nivel, ingresó a la Escuela Nacional Preparatoria. En el año de 1936, al conseguir el cambio de turno en su lugar de trabajo, se matriculó en las Facultades de Derecho, en el turno matutino, y en la de Filosofía y Letras, en el turno vespertino, ambas de la Universidad Nacional Autónoma de México (UNAM). Al cumplir el primer año de sus estudios universitarios, abandonó la Facultad de Derecho pues optó por seguir la formación humanística.</p>

                      <p>El gobierno de Lázaro Cárdenas del Río fue solidario con los republicanos españoles, a muchos de los cuales acogió, entre ellos a un amplio número de intelectuales. Tal fue el caso de José Gaos a quien Leopoldo Zea conoció en cursos de la UNAM y por cuya intervención obtuvo una beca de La Casa de España en México, por lo cual dejó de trabajar y pudo dedicarse de manera exclusiva a los estudios filosóficos.</p>

                      <p>Al terminar sus cursos profesionales de filosofía, se matriculó, primero en la maestría de filosofía de la Facultad de Filosofía y Letras de la UNAM y luego, entre 1942 y 1943, en el doctorado de filosofía en la misma institución. Durante cuatro años fue becario de El Colegio de México dedicándose a preparar sus tesis de maestría y de doctorado, ambas bajo la dirección de José Gaos. Así en 1943, con el trabajo El positivismo en México, obtuvo el grado de maestro en filosofía, habiendo sido aprobado con la distinción Magna Cum Laude, y en 1944 obtuvo el grado de doctor en filosofía con la tesis Apogeo y decadencia del positivismo en México, aprobado con la distinción Summa Cum Laude.</p>

                      <p>Su formación académica la completó y consolidó al aprovechar una beca de año y medio, entre 1945 y 1946, otorgada por la Fundación Rockefeller para continuar sus trabajos sobre pensamiento en América Latina, que le permitió visitar e investigar en diversos centros culturales y educativos, de los Estados Unidos primero, y de América Latina después.</p>

                      <p>De modo que su actividad intelectual, desde los años cuarenta del siglo pasado, la desplegó en distintas direcciones, resultando complementarias por los propósitos de lograr una mayor comprensión para realizar reflexiones agudas y originales sobre los procesos socioculturales, económicos y políticos de América Latina. En efecto, Leopoldo Zea sedesempeñó como catedrático, investigador, analista, difusor, funcionario e inspirador de múltiples empresas culturales.</p>

                      <p>Los retos y logros obtenidos por los diferentes roles desempeñados constituyen el respaldo de los múltiples reconocimientos recibidos en vida. Los que a la vez resultan testimonio del significado e impacto de su obra intelectual: Profesor Emérito de laUNAM (México, 1975); Bolivariano Emérito, reconocimiento otorgado por la Federación Internacional de Sociedades Bolivarianas (Caracas, 1979); Premio Nacional de Ciencias y Artes (México, 1980); Comendador de la Orden del Libertador, otorgado por el gobierno de Venezuela (Caracas, 1982); Doctor Honoris Causa de la Universidad de París X (1984); Doctor Honoris Causade la Universidad Lomonosov (Moscú, 1984); Doctor Honoris Causa de la Universidad de la República de Uruguay (Montevideo, 1985); Doctor Honoris Causa de la Universidad Nacional Autónoma de México (1985); Orden Alfonso X El Sabio con banda otorgada por el gobierno de España (1985); Premio Interamericano de Cultura “Gabriel Mistral” otorgado por la OEA (1987); Doctor Honoris Causa de la Universidad Autónoma del Estado de México (Toluca, 1987); Doctor Honoris Causa de la Universidad Nacional de Cuyo (Mendoza, Argentina, 1993);Doctor Honoris Causa de la Academia de Ciencias de Rusia (Moscú, 1993);Doctor Honoris Causa de la Universidad Nacional y Capodistriaca de Atenas, Grecia (1997); Doctor Honoris Causa de la Universidad de Santiago de Chile (1997); Doctor Honoris Causa de la Universidad de La Habana (1997); Condecoración Orden del Libertador en grado de Gran Oficial de parte del gobierno de Venezuela (Caracas, 1997); Medalla Belisario Domínguez por el Senado de la República (México, 2000).</p>



                      <h5>VOCACIÓN DE SERVICIO</h5>

                      <p>Las distintas funciones desempeñadas a lo largo de su vida denotan su vocación de servicio por las causas más nobles como la promoción del conocimiento de la realidad latinoamericana para forjar un proyecto de sociedad profundamente humanista, enel que todas las sociedades participen en igualdad de condiciones desde sus propias diferencias. Su vinculación a la docencia empezó en 1942 en la Escuela Nacional Preparatoria al sustituir a Samuel Ramos en la cátedra de Introducción a la Filosofía; en los años 1943-1944 impartió clases en la Escuela Normal de Maestros; durante 1944 dictó un curso en El Colegio de México, y en este mismo años se incorporó a la Facultad de Filosofía y Letras de la UNAM donde sustituyó a Antonio Caso en su cátedra de Filosofía de la Historia. A partir de entonces, en tal institución, impartió diversos cursos tanto en licenciatura como en posgrado, resaltando la fundación del Seminario sobre Historia de las Ideas en América, en 1947. En el año de 1966 fue designado profesor de tiempo completo de la Facultad de Filosofía y Letras de la UNAM, situación que mantuvo por más de treinta y ocho años. En ella promovió la creación de la Licenciatura, Maestría y Doctorado en Estudios Latinoamericanos.</p>

                      <p>Su quehacer en el ámbito de la investigación, tan prolija en resultados, la inició en El Colegio de México, cuando fungió como investigador durante los años 1947-1953con la línea de trabajo sobre la filosofía, el pensamiento y las ideas en América. Luego pasó a la UNAM donde fue designado investigador de tiempo completo en el Centro de Estudio Filosóficos entre 1954 y 1965, pero que interrumpió durante el período 1960-1965 por el desempeño de una comisión como Director de Relaciones Culturales en la Secretaría de Relaciones Exteriores. A su regreso a la UNAM, como Director en la Facultad de Filosofía y Letras, siguió desarrollando labores de investigación, cuyos impactos sustentaron que en 1984 se le nombrara Investigador Nivel III del Sistema Nacional de Investigadores.</p>

                      <p>En el ámbito de la administración académica y pública, son diversas las posiciones desempeñadas por Leopoldo Zea. Entre 1948 y 1953 fue Secretario de la Facultad de Filosofía y Letras de la UNAM. De 1959 a 1961 fungió como Director del Instituto de Investigaciones Políticas, Económicas y Sociales del Partido Revolucionario Institucional; de 1960 a 1966 le toco crear la Dirección General de Relaciones Culturales de la Secretaría de Relaciones Exteriores, de la cual fue Director con el carácter de Enviado Extraordinario y Ministro Plenipotenciario. Durante los años 1966-1970 dirigió la Facultad de Filosofía y Letras de la UNAM; entre los años de 1970 y 1972 colaboró como Director General de Difusión Cultural de la UNAM durante el breve rectorado de Pablo González Casanova; en 1978 se le nombró Coordinador Interino del Centro Coordinador y Difusor de Estudios Latinoamericanos (CCYDEL), y de 1982 a 1990 fungió como Director del mismo. A partir de 1990 tuvo como última responsabilidad la dirección del Programa Universitario de Estudios Latinoamericanos de la UNAM.</p>

                      <p>En el ámbito de la difusión cultural Leopoldo Zea debe ser ubicado comocontinuador de la labor iniciada por José Antonio Alzate en el siglo XVIII, Ignacio Manuel Altamirano, en el siglo XIX y José Vasconcelos en la primera mitad del siglo XX, y también promovida por sus contemporáneos como los casos del periodista Fernando Benítez y del escritor Octavio Paz. A diferencia de ellos, sus actividades de promoción cultural las desplegó desde la UNAM, principalmente, con los propósitos de despertar y cultivar el interés por el conocimiento de Latinoamérica, de modo que sus responsabilidades de funcionario, como presidente o coordinador de sociedades científicas, organizador de eventos, director o editor de revistas, colecciones, etc. permiten mostrar sus amplios esfuerzos en ese sentido. Como reconocimiento a su manifiesto interés por fomentar la difusión cultural y la extensión universitaria se le nombró Presidente del Comité de Historia de las Ideas en América, del Instituto Panamericano de Geografía e Historia (1947); Vicepresidente de la Sociedad Iberoamericana de Filosofía (1960); Primer Presidente de la Asociación Filosófica de México (1968); Director Ejecutivo del Consejo Nacional de Difusión Cultural (1971); Presidente de la Segunda Conferencia Latinoamericana de Difusión Cultural y Extensión Universitaria (1972); Asesor Fundador del Centro de Estudios Latinoamericanos “Rómulo Gallegos” de Caracas, Venezuela (1974); Coordinador de la Federación Internacional de Estudios sobre América Latina y del Caribe (FIEALC) desde 1978; Coordinador General de la Sociedad Latinoamericana sobre América Latina y el Caribe (SOLAR) desde 1978; Presidente de la Sociedad Interamericana de Filosofía (1985).</p>

                      <p>Con relación a su incansable actividad como promotor, organizador, coordinador y participante de eventos académicos, resultó relevante su intervención en el II Congreso Interamericano de Filosofía (Nueva York, 1947) y a partir de entonces anualmente ponente invitado en casi todos los actos sobre asuntos culturales latinoamericanos efectuados tanto en México como el extranjero. En 1950 organizó el III Congreso Interamericano de Filosofía que tuvo por sede la ciudad de México; en 1963 formó parte del Comité Organizador del XIII Congreso Internacional de Filosofía efectuado en la ciudad de México; en 1965 participó en la organización del I Encuentro Siglo XX sobre la América Latina reunido en Cuernavaca, México; en 1976 organizó el Coloquio sobre Filosofía e Independencia dentro del XXX Congreso Internacional de Ciencias Humanas en Asia y África del Norte, patrocinado por la UNESCO en la ciudad de México; inspiró y colaboró en la organización del I, II y III Simposium para la Coordinación y Difusión de los Estudios Latinoamericanos, respectivamente, en México 1978, Caracas 1980 y Río de Janeiro 1982; en 1985 organizó el XI Congreso Interamericano de Filosofía, en Guadalajara, México. Colaboró en la realización de diez Congresos de la FIEALC cuyas sedes fueron Brasil, Chile, España, Francia, Israel, Japón, Polonia, Rusia, Taiwán y Venezuela y ocho Congresos de SOLAR efectuados en Argentina, Brasil, Chile, México, Nicaragua y Trinidad y Tobago; así como de tres Congresos Internacionales de Filosofía y Cultura del Caribe llevados a cabo en Colombia, México y Argentina.</p>

                      <p>Sus funciones editoriales fueron pródigas y semilleros de vocaciones latinoamericanistas, por los rubros contenidos en las revistas que dirigió, tales los casos de Tierra Nueva (1940-1942); Historia de las Ideas en América (1959-1961); Anuario Latinoamérica (1968-1994); Deslinde (1968-1970); Revista de la Universidad de México (1970), y Cuadernos Americanos (1987-2004). Complementan ese rol sus responsabilidades asumidas en la dirección de colecciones o libros sobre temas latinoamericanos como los casos siguientes: “México y lo mexicano” de la Editorial Porrúa (1952-1956); “Historia de las Ideas en América” (1956) y “Tierra Firme” (1974) editadas por el Instituto Panamericano de Geografía e Historia (IPGH) y el Fondo de Cultura Económica (FCE); “Latinoamérica. Cuadernos de Cultura Latinoamericana” de la UNAM (1978-1979); “Nuestra América” de la UNAM (1982); “500 años después” de la UNAM (1990); “Panoramas de Nuestra América de la UNAM (1992); “Latinoamérica fin de milenio” del IPGH y el FCE (1999-2001) en tres series: “La cultura latinoamericana de fin de siglo y de milenio” (cinco volúmenes), “98 Reconciliación iberoamericana” (cinco volúmenes) y “Humboldt, el otro descubrimiento” (seis volúmenes). En 2002 inició la colección “Latinoamérica en la globalización y el tercer milenio” también auspiciados por el IPGH, el FCE y la UNAM.</p>

                      <p>Su interés por animar los estudios latinoamericanos explica la creación del Grupo Filosófico Hiperión del que formaron parte Ricardo Guerra, Jorge Portilla, Salvador Reyes Nevares, Joaquín Sánchez Mcgregor, Fausto Vega, Luis Villoro, en 1953. En 1967 inspiró la creación de los Estudios Latinoamericanos en los niveles de Licenciatura, Maestría y Doctorado en la Facultad de Filosofía y Letras de la UNAM; los apoyos a la creación del Centro de Estudios Latinoamericanos “Rómulo Gallegos” de Caracas, Venezuela; su vinculación con la Maestría en Estudios Latinoamericanos de la Universidad Autónoma del Estado de México (UAEM), creada en 1974, y su colaboración para consolidar el Instituto de Graduados de Estudios Latinoamericanos de la Universidad de Tamkang, Taiwán, establecido en 1989.</p>

                      <p>Además Leopoldo Zea colaboró en las principales publicaciones periodísticas de México y de Argentina, Bolivia, Brasil, Colombia, Ecuador, España, Estado Unidos, Francia, Uruguay, Venezuela, etc. Incluso como responsable de suplementos culturales y principalmente como articulista de diarios como Novedades desde 1956 hasta su desaparición en 2002; Excélsior; El Nacional; El Día.</p>



                      <h5>GENESIS DE SU OBRA Y CONTRIBUCIONES AL FILOSOFAR</h5>

                      <p>Sintetizar los planteamientos de Leopoldo Zea contenidos en su abultada producción bibliohemerográfica y desarrollada a lo largo de su longeva vida representa todo un reto, pero resulta pertinente para aportar elementos que inviten a su revisión con el noble propósito de elaborar otras valoraciones.</p>

                      <p>Un modo didáctico, como puede seguirse en la exposición de las ideas de Leopoldo Zea, lo constituye el criterio cronológico que él mismo promovió hace una década cuando se interrogó: “¿y qué con la filosofía? Después el Positivismo en México,la preocupación por el ser y la cultura del mexicano y luego una historia de las ideas en Latinoamérica y la preocupación por la Filosofía de su historia, a la que estaba condenado según mi maestro Gaos” (L. Zea, Filosofar a la altura del hombre, 1993, p. 17), vino la elaboración de la filosofía de la liberación latinoamericana que desembocó en la praxis de la filosofía como instrumento para promover un proyecto humanista de alcance mundial, desde la realidad latinoamericana.</p>

                      <p>La génesis del quehacer filosófico de Leopoldo Zea la describió él mismo en los términos siguientes.</p>

                      <p>En la preparatoria recibí mis primeras lecciones de filosofía, lecciones para mí forzadas porque no entendía nada... Entré como estudiante de licenciatura en 1936 a la Facultad de Filosofía y Letras de la Universidad Nacional Autónoma de México. Uno de mis maestros de literatura, Rubén Salazar Mallén, dio un curso sobre Ortega y Gasset, cuya filosofía me pareció comprensible. Pasé al curso del Maestro Samuel Ramos, también dedicado a Ortega. La filosofía tomaba para mí otro sentido, la comprendía. Seguí los cursos del Maestro Antonio Caso y de Eduardo García Máynez. Entendía lo que ellos explicaban y esta comprensión me permitía a su vez encontrar sentido al mundo externo en que me estaba formando. A partir de 1938 año de llegada del transtierro español, tomé cursos con Joaquín Xirau, Luis Recaséns Siches, Juan Roura Parella, José Medina Echavarría, y, especialmente José Gaos. Me encontré con él y, por su iniciativa mi vida cambió y me inclinaría decididamente hacia el campo de la filosofía. Con él aprendí a comprender la filosofía que antes me parecía incomprensible. Fue un hecho; mi vocación se decidía por la filosofía. Así continué y cumplí mis estudios: Maestro y Doctor en Filosofía. (Ibídem, P.16).</p>



                      <p>De modo que en su formación académica intervinieron los principales y más connotados pensadores mexicanos y españoles exiliados, quienes lo pondrían en contacto con la producción intelectual que le ayudaría a consolidar su peculiar manera de entender y practicar la filosofía, como el “raciovitalismo de Ortega, la sociología del saber de Scheler, la sociología del conocimiento de Manheim y Weber, el existencialismo de Heidegger y Sartre, el historicismo de Dilthey y la escuela de Frankfurt [que] me ofrecía, en su momento, los instrumentos de comprensión para entender más y más mi mundo, mi circunstancia vital e histórica, mi situación.” [Ibídem, p.16], y el total respaldo de José Gaos, su maestro siempre recordado, por cuanto lo estimuló a atender la realidad mexicana y americana.</p>



                      <h5>FILOSOFÍA</h5>

                      <p>Completaría su formación con la compenetración de la historia de las ideas de América y por sus vivencias, productos del recorrido por toda América Latina, Estado Unidos, La URSS, Europa, África y Asia, y los contactos y amistad con personajes como Werner Jaeger, Maurice Merleau-Ponty, Arnold Toynbee, etc. En consecuencia el quehacer reflexivo de Leopoldo Zea, con tales fuentes e influencias contribuyó a la superación del complejo de la supuesta incapacidad para filosofar desde América Latina, sobre la base historicista de explicar e interpretar al hombre y sus producciones a partir de sus circunstancias, considerando el momento histórico dentro de una perspectiva concéntrica, que a decir de José Gaos va de México a América y de ella a la comunidad internacional de los hombres, quien destacará la notable influencia de Federico Hegel (José Gaos “México, tema y responsabilidad” en Ibídem, pp.114, 123).</p>

                      <p>Además Leopoldo Zea cultivó como virtud erigirse en eco y voz de la cultura latinoamericana y lo hizo como miembro de la generación más creativa de nuestra intelligentia, la que durante las décadas de los años sesenta y setenta mostró la madurez del latinoamericanismo, entre quienes pueden mencionarse a los economistas dependistas como Raúl Prebisch; de la sociología de la dependencia como Sergio Bagú, Pablo González Casanova, Fernando Henrique Cardoso, Gino Germani; de la teología de la liberación como Gustavo Gutiérrez y Leonardo Boff; de la pedagogía de la liberación como Paulo Freire; del boom de la literatura latinoamericana como Miguel Ángel Asturias, Julio Cortázar, Carlos Fuentes, Gabriel García Márquez, Pablo Neruda, Octavio Paz, Roa Bastos; de la antropología de la liberación como Darcy Ribeiro, y de la filosofía de la liberación como Arturo Ardao, Enrique Dussel, Arturo Andres Roig.</p>

                      <p>A partir de ese ambiente y bagaje cultural resulta pertinente resaltar la conceptuación que cultivó de la filosofía, punto de partida ineludible para comprender las implicaciones de su quehacer intelectual. En principio hay que señalar que para Leopoldo Zea es una actividad intelectual comprometida [L. Zea, La filosofía americana como filosofía sin más, 1969, p.72], es saber útil, orientador y esclarecedor de la realidad para atender los problemas existentes al ubicarlos dentro de las propias circunstancias con el propósito de buscar soluciones convincentes. Para el efecto estableció una clara diferenciación entre la problemática que le es propia y el instrumental para operar. En el primer caso la filosofía es verdad histórica circunstancial, y en el segundo es concreción o empleo de la racionalidad porque en occidente, apunta, nació con el principio dual del logos: razón ypalabra.</p>

                      <p>Tal conceptuación le permitió justificar el ejercicio de la actividad filosófica a partir y desde las circunstancias latinoamericanas como expresión auténtica, comprometida e iluminadora y racionalizadora de la realidad regional, con lo que se contribuyó a su universalización en tanto exista la capacidad de ser comunicada por unos y comprendida por otros. Es un quehacer que se despliega como diálogo con las circunstancias, en consecuencia trata de resolver los problemas que éstas plantean, pues “la filosofía ha dado siempre respuestas en función de la problemática de un tiempo y de un lugar determinados. La filosofía responde a los problemas concretos que se plantea el ser humano y sin las cuales no tendrá razón de ser”. (L. Zea, América como conciencia, 1953, p.44).</p>



                      <p><h5>CATEGORÍAS Y METODOLOGÍA</h5></p>

                      <p>La filosofía de Leopoldo Zea requiere de la comprensión y relación de una amplia gama de categorías, las cuales constituyen el marco conceptual inneludible para internarse en la revisión de sus obras o que hay que tener en cuenta en la lectura de cada uno de sus textos. Ellas resultan entendibles por el contexto en que se emplean.</p>

                      <p>Esta es la relación de las principales categorías: americanismo, asimilación, asunción, autenticidad, autodeterminación, barbarie, circunstancia, coloniaje, conciencia, cultura, decadencia, discurso, emancipación, explotación, historia, humanismo, identidad, igualdad, imitación, integración, interdependencia, latinoamericanismo, liberación, libertad, marginación, nacionalismo, originalidad, pensamiento, proyecto, pueblo, realidad, transformación, utopía, yuxtaposición.</p>

                      <p>Tales términos pueden localizarse en todas sus obras y reflejan las tres fases de su evolución intelectual, de modo que algunas tienen mayor recurrencia en los años en que atendió prioritariamente los tópicos de historia de las ideas; otras en la fase de su filosofía de la liberación, y, también, de manera integradora en su etapa humanista. Muchas de esas categorías han sido muy discutidas, dando origen a polémicas que Zea no rehuyó, pero a veces han impedido visualizar la amplia obra de nuestro biografiado.</p>

                      <p>Ciertamente Leopoldo Zea no creó ningún sistema, pero sí puede ser considerado el principal promotor de una filosofía sin más, la filosofía de la liberación latinoamericana con la que nuestros países están contribuyendo a enriquecer el pensamiento occidental, en el afán de otorgarle su verdadera dimensión universal, proceso en el que participan intelectuales de otros continentes.</p>

                      <p>La autenticidad de su quehacer filosófico consistió en redimensionar el origen mismo de la filosofía con la pretensión de mostrar la existencia de otras formas de interpretar la realidad a partir de un enfoque interdisciplinario, de implícitas críticas a las posturas europeístas e indoamericanistas.</p>

                      <p>Sobre su modo de investigar y exponer sus resultados señaló la recurrencia al empleo de “... métodos, sistemas, filósofos y filosofías diversas que encuentro, que me ayudan a comprender mejor la no menos compleja realidad que trato de racionalizar, partiendo de experiencias adquiridas o que considero menesteres adquirir, e incluyendo instrumentos que antes me fueran desconocidos y, de ser posible, inventando al organizar lo recibido. Me es difícil jurar por un filósofo y limitarme a un sistema o a una metodología. La verdad que pretendo comprender, racionalizar, es extraordinariamente compleja como para que se deje apresar con un método supuestamente universal, lo cual sólo se alcanza al anular la realidad” (L. Zea, Filosofar a la altura del hombre, p. 89)</p>



                      <p>Con base en tal manera de sustentar sus reflexiones, totalmente heterodoxa, pasemos a revisar sus principales planteamientos.</p>



                      <h5>INTERPRETACIÓN DE CULTURA</h5>

                      <p>Uno de los primeros y constantes tópicos en los que sustentó su praxis filosófica lo constituyeron sus reflexiones sobre la cultura, para lo cual desplegó una amplia, fecunda y profunda labor interpretativa que permite identificarlo como uno de los pensadores latinoamericanos que más ha contribuido al desarrollo de la filosofía de la cultura. Para él “cultura es cultivo, esto es formación, conformación. Algo que hace al hombre por sí mismo, en la inevitable relación con sus semejantes. La cultura es algo que necesariamente, tiene el hombre que formar de lo que sus semejantes hacen,realizan, creando a su vez el horizonte de posibilidades de la misma, posibilidades pero no limitación. ( L. Zea. Filosofía y cultura latinoamericana, 1976, p.164).</p>

                      <p>Sus reflexiones sobre cultura le ocuparon una amplia gama de tópicos como determinar su origen, consustancial a la actividad de todos los seres humanos cuyos intercambios son la fuente de riqueza y pluralidad de manifestaciones; el reconocimiento de su carácter circunstancial con lo que explicó la existencia de tipos de cultura sea mediante criterios geográficos, políticos, económicos, étnicos, etc.; la determinación de distintos roles, como los de tipo pedagógico y</p> <p>social, etc. Así justificó la existencia de la cultura latinoamericana con el propósito de promover su necesaria participación en la superación de la crisis cultural de occidente por el derrumbe de sus valores propalados como universales al sustentar: “… coincidiendo con el fin de la segunda guerra y la problemática que ésta origina en su pensamiento y filosofía, vuelve a surgir el problema de la posibilidad o existencia de una cultura originalmente latinoamericana... América y Europa se encontraban en el mismo plano en la situación de tener que hacer o rehacer su cultura... Ahora, tanto europeos como americanos tenían que preocuparse por apuntalar las bases de una cultura que fuese menos frágil que la que hasta ayer parecía modelo para la eternidad. Europeos y americanos tenían que partir, no de cero, sino de las propias y concretas experiencias para no repetir errores, ni crear nuevos espejismos” (L. Zea, El pensamiento latinoamericano, 1976, p. 483).</p>

                      <p>De esta forma promovió la pertinencia de forjar una cultura sustentada en ideas y creencias propias, que trascendiera la dependencia, o sea para “… completar la hazaña de la emancipación política con la de la libertad por la cultura” (L. Zea. Descubrimiento e identidad latinoamericana, 1990, p. 50), reconociendo no sólo la pluralidad sino la existencia y fomento del multiculturalismo por la acción de la autonomía cultural y como resistencia a la homogenización de la</p> <p>cultura occidental. Sólo así podrá concretarse la independencia cultural.</p>



                      <h5>FILOSOFÍA DE LA HISTORIA</h5>

                      <p>Con base en la concepción de la cultura como cualquier acto de creación o transformación espiritual y material, la filosofía resulta ser una manifestación más de ella, por la que al invocar y justificar la existencia de la cultura latinoamericana por extensión lo llevará al reconocimiento y promoción de la filosofía latinoamericana: “La conciencia filosófica ha venido a ser... expresión de madurez cultural” (L. Zea, Filosofía y cultura latinoamericana, p. 15), por lo que consideró como rol del filósofo comprender tan alta responsabilidad para actuar en consecuencia.</p>

                      <p>En su caso particular desplegó su quehacer filosófico para coadyuvar en el desenvolvimiento de la creatividad de los latinoamericanos recurriendo a la recuperación de la historia, donde localizó la esencia del ser humano, con lo que incursionó en el desarrollo de la filosofía de la historia cuya trayectoria será evidenciada fehacientemente por su obra al ir del estudio del caso mexicano al latinoamericano y finalmente integrarlos en la perspectiva mundial. Los saldos de sus reflexiones al respecto consistieron en: 1) construir un discurso desde las circunstancias latinoamericanas; 2) cuestionar la supuesta universalidad de la historia de la filosofía occidental al “desenmascarar su provincialismo eurocentrista” (José Luis Gómez Martínez en www.ensayistas.org); 3) recuperar no sólo el conocimiento de los hechos históricos, sino sobre todo destacar el sentido y proyección de ese conocimiento y, 4) fomentar la realización de la historia de las ideas nacionales y luego latinoamericana, según José Gaos (“México tema y responsabilidad” en L. Zea, Filosofar a la altura del hombre, p.121).</p>

                      <p>Así Leopoldo Zea elaboró una filosofía de la historia como respuesta a nuestras circunstancias y como subversión para recuperar el pasado, con lo cual generó nuevas temáticas de reflexión.</p>



                      <h5>HISTORIA DE LAS IDEAS</h5>

                      <p>Con base en dicha praxis filosófica, Leopoldo Zea produjo una basta obra que puede clasificarse en tres momentos. A la primera fase de su actividad filosófica corresponden sus trabajos de historia de las ideas que pueden ubicarse entre 1942 y 1969. A la segunda fase pertenecen las obras de filosofía de la liberación particularmente los textos de las décadas de los años setenta y ochenta del siglo XX. A la tercer fase corresponden los trabajos sobre humanismo, en particular los de los años noventa de la centuria anterior hasta su muerte.</p>

                      <p>Fue precisamente su tan recordado maestro José Gaos quien destaca parte de esa diferenciación de su desarrollo intelectual y quien así le marcó sus derroteros filosóficos cuando comentó la aparición de su obra Dos etapas del pensamiento en Hispanoamérica, (1949): “Creo, querido Leopoldo, que este libro confirmará definitivamente la consideración, en que ya se le tiene a usted internacionalmente, de ser uno de los maestros en materia en historia de las ideas en nuestros países, mientras espero que se le llegue a tener por uno de los maestros de la filosofía, en estos países y por lo mismo sin limitaciones de lugar y tiempo... creo lo uno y espero lo otro...” (José Gaos, “Carta abierta a Leopoldo Zea” en Cuadernos Americanos,No. 1, enero- febrero 1950, p. 161).</p>

                      <p>En efecto, Leopoldo Zea había iniciado historiar las ideas en nuestro país particularmente sobre el positivismo en México y por el contacto con un selecto grupo de intelectuales latinoamericanos con preocupaciones idénticas que participaban en la recuperación de las historias del pensamiento de sus países como los casos de Arturo Ardaro (Uruguay), Joâo Cruz Costa (Brasil); Guillermo Francovich (Bolivia), Ernesto Mayz Vallenilla (Venezuela); Francisco Miró Quezada (Perú); Félix Schvarzman (Chile). Tomando como base esa producción y aprovechando los intercambios con tales intelectuales, Leopoldo Zea efectuó los primeros trabajos globales sobre historia de las ideas en América Latina de manera específica en el libro comentado por Gaos, el cualenriquecióy años más tarde reeditó con el título Pensamiento latinoamericano (1965) donde articula una condensada y rica exposición, palpándose su preocupación por mostrar la existencia de reflexiones en torno a los más diversos rubros de las circunstancias de nuestros países y, sobre todo, destacando la necesidad de independencia intelectual.</p>



                      <h5>FILOSOFIA DE LA LIBERACIÓN</h5>

                      <p>Siguiendo el programa intelectual que le trazó José Gaos paso a exponer sus planteamientosacerca de su filosofía propiamente dicha, cuya singularidad ha consistido en promover el conocimiento para la liberación. El texto que puede tomarse como puente entre sus preocupaciones de historiador de las ideas y filósofo de nuestras circunstancia lo constituye La filosofíaamericana como filosofía sin más aparecido en 1969 como respuesta al libro de Augusto Salazar Bondy, ¿Existe una filosofía de nuestra América? (1968), y que dedicó a la memoria del maestro José Gaos, donde recuperó la veta de que la filosofía en América inició con el problema del hombre, señalando su originalidad y clarificando que la filosofía es más que ciencia rigurosa e ideología, por ser saber ético, concluyendo que su autenticidad consiste en pensar desde nuestra circunstancia, lo cual significa hacer filosofía sin más, cuya función será conscientizadora de la condición de subordinación y a partir de tal autognosis promover las formas para superar tal situación ( L. Zea, La filosofía americana como filosofía sin más, 1969, p. 160).</p>

                      <p>Luego vino la conferencia “La filosofía latinoamericana como filosofía de la liberación” expuesta en Argentina (1973), precisamente durante la irrupción en ese país de posiciones semejantes y continuará con planteamientos como el siguiente: “… no seremos libres por haber cancelado el subdesarrollo; más bien habremos cancelado el subdesarrollo por sabernos hombres libres” (L. Zea, Dialéctica de la conciencia americana, 1976, p.225),posición que antes había ratificado al suscribir la “Declaración de Morelia. Filosofía e independencia” (1975) firmada también por Enrique Dussel, Francisco Miró Quesada, Arturo Andrés Roig y Abelardo Villegas, donde se esbozan bases de la filosofía de la liberación para propugnar su alcance universal, como el reconocimiento de la dependencia, la toma de conciencia, el enriquecimiento del pensamiento filosófico con los avances de las ciencias sociales y humanas, y la consideración de la experiencia latinoamericana, todo ello para trastocarla en filosofía de la liberación mundial.</p>

                      <p>Tal manera de concebir su praxis filosófica proviene del conocimiento y comprensión de los planteamientos de los más preclaros expositores del pensamiento latinoamericano. Así en 1980 la sustancia al decir que Simón Bolívar planteó los principales problemas que debe y había venido atendiendo nuestra filosofía: “… el problema de la identidad, ¿quiénes somos los hombres de esta América?; el problema de ladependencia, ¿por qué somos así?; el problema de la libertad, ¿podemos ser de otra manera?, y el problema de la integración, ¿integrados en la dependencia, podemos integrarnos en la libertad?” (L. Zea, Simón Bolívar. Integración en la libertad, 1980, p. 8)</p>

                      <p>En general, la filosofía de la liberación de Leopoldo Zea no sólo está contenida en su producción intelectual, sino encarnó en sus actitudes que lo llevaron a identificarlo como un pensador molesto e incluso profeta irritante (“Leopoldo Zea ¿Profeta irritante?”, Cuadernos Americanos, Nueva Época, N° 34, julio- agosto 1992, pp. 251-256), por ser un deconstructor del pensamiento eurocentrista y forjar un discurso desde la periferia con proyección global.</p>



                      <h5>NUEVO HUMANISMO</h5>

                      <p>El origen y la propuesta del quehacer filosófico de Leopoldo Zea giran en torno a la preocupación sobre el ser y destino del hombre. Toda su filosofía puede sintetizarse como discurso antropológico, y por sus propósitos deconstructivos del pensamiento occidental identifica la existencia de: “Dos ideas sobre el hombre... El occidental ha hecho de su propia humanidad el índice negativo de la humanidad de los otros hombres. Los otros hombres, por el contrario, no aceptan esta idea y proclaman la propia, aquella en que se destaca el inhumanismo de la filosofía occidental y el acendrado humanismo de una filosofía que concede humanidad a todos los hombres, incluyendo a los deshumanizados occidentales. Dos ideas del hombre que han propugnado y pugnan por prevalecer... (L. Zea, La filosofía americana como filosofía sin más, p. 137)</p>

                      <p>De modo que su pensamiento liberador evidencia los límites antropológicos de la filosofía occidental y propugna un nuevo humanismo sustentado en el interés de revelar el significado mismo de la palabra hombre, el cual sólo resulta comprensible si se relaciona con una situación determinada, dentro de contextos sociales específicos.</p>

                      <p>Con base en la ubicación sociohistórica y cultural del hombre, Leopoldo Zea patentizó tanto la identidad igualitaria en sus diferencias especificas que expuso en los términos siguientes “Todos los hombres son iguales entre sí por ser todos y cada uno de ellos peculiares, esto es, por ser individuos, personas, y que, no por serlo, están desligados de las expresiones propias de los humanos. ‘Existo,luego soy’ es la conciencia de esta existencia, el punto de partida de la más original, pero al mismo tiempo, más concreta afirmación de la existencia”(L. Zea, Filosofar a la altura del hombre, p. 376). Es la esencia misma del hombre, la que le da identidad en tanto ésta la define como la vivencia personal que revela, expresa y constituye.</p>

                      <p>Sobre la base del reconocimiento de la igualdad de los hombres en sus diferencias, la extiende a los pueblos, atribuyendo el establecimiento derelaciones interculturales para concretar los principios del nuevo humanismo, verdaderamente universal, el cual debe considerarse síntesis y aspiración final de su filosofía, que identifico como la tercera fase de su evolución intelectual, al insistir en la posibilidad y necesidad de un nuevo proyecto societario, el humanista, único modo de acabar con las situaciones de dependencia política, económica, social, cultural, etc., el cual advendrá como consecuencia de la necesidad de transformar la conciencia del hombre.</p></p>

                      <h5>LIBROS DE LEOPOLDO ZEA</h5>

                      <p>1943. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-positiv.htm"><em>El positivismo en México</em></a>. México: El Colegio de México.</p>
                      <p>1944. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-positiv.htm"><em>Apogeo y decadencia del positivismo en México</em></a>. México: El Colegio de México</p>
                      <p>1945. <em>En torno a una filosofía americana</em>. México: El Colegio de México.</p>
                      <p>1948. <em>Ensayos sobre filosofía en la historia</em>. México: Stylo.</p>
                      <p>1949. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-pla1.htm"><em>Dos etapas del pensamiento en Hispanoamérica</em>. Del romanticismo al positivismo</a>. México: El Colegio de México.</p>
                      <p>1952. <a target="_blank"  href="file:///A:\zconcien.htm"><em>Conciencia y posibilidad del mexicano</em></a>. México: Porrúa y Obregón.</p>
                      <p>1952 <em>La filosofía como compromiso y otros ensayos</em>. México: Fondo de Cultura Económica, Col. Tezontle</p>
                      <p>1953. <a target="_blank"  href="file:///A:\filosofos\mexico\zea\bibliografia\acc\"><em>América como conciencia</em></a>. México: Cuadernos Americanos.</p>
                      <p>1953 <a target="_blank"  href="file:///A:\zconcien.htm"><em>El Occidente y la conciencia de México</em></a>. México: Porrúa y Obregón.</p>
                      <p>1953 La conciencia del hombre en la filosofía. Introducción a la filosofía. México: Imprenta Universitaria, 1953 (a partir de 1960 se edita de nuevo bajo el título de Introducción a la filosofía. La conciencia del hombre en la filosofía).</p>
                      <p>1955. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-fienme.htm"><em>La filosofía en México</em></a>. México: Editora Ibero-Mexicana (dos volúmenes con paginación correlativa).</p>
                      <p>1955 <em>América en la conciencia de Europa</em>. México: Los Presentes.</p>
                      <p>1956 Del liberalismo a la revolución en la educación mexicana. México: Talleres Gráficos de la Nación.</p>
                      <p>1956 Esquema para una historia de las ideas en Iberoamérica. México: UNAM.</p>
                      <p>1957. <a target="_blank"  href="file:///A:\zameenhi.htm"><em>América en la historia</em></a>. México: Fondo de Cultura Económica.</p>
                      <p>1959. <em>La cultura y el hombre de nuestros días</em>. México: Imprenta Universitaria.</p>
                      <p>1960. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-alyem.htm"><em>Latinoamérica y el mundo</em></a>. Buenos Aires: EUDEBA (las citas del texto provienen de la edición de 1965).</p>
                      <p>1960 Introducción a la filosofía. La conciencia del hombre en la filosofía. México: UNAM.</p>
                      <p>1960 Dos ensayos: Del liberacionismo a la Revolución. El problemacultural América-Latina. Valencia, Venezuela: Universidad de Carabobo.</p>
                      <p>1963. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-tlam.htm"><em>The Latin-American Mind</em></a>. Norman: University of Oklahoma Press.</p>
                      <p>1965. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-pla1.htm"><em>El pensamiento latinoamericano</em></a>. México: Pormaca, 2 vols. (Edición aumentada de Dos etapas del pensamiento en Hispanoamérica. En 1976 se publicó de nuevo muy aumentado en la Editorial Ariel)</p>
                      <p>1968.<a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-positiv.htm"><em>El positivismo en México: Nacimiento, apogeo y decadencia</em></a>. México: Fondo de Cultura Económica (las citas del texto provienen de la edición de 1975).</p>
                      <p>1968 <em>Antología de la filosofía americana contemporánea</em>, México, Costa AMIC, Col. Pensamiento de América, 2ª. Serie, vol. 7.</p>
                      <p>1969 <a target="_blank"  href="file:///A:\zfiamco.htm"><em>La filosofía americana como filosofía sin más</em></a>. México: Siglo Veintiuno (las citas del texto provienen de la edición de 1980).</p>
                      <p>1969<a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-alyem.htm">Latin America and the World</a>. Norman: University of Oklahoma Press (<a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-alyem.htm"><em>América Latina y el mundo</em></a>, 1960).</p>
                      <p>1971 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-leyn.htm"><em>Latinoamérica: emancipación y neocolonialismo</em></a>. Caracas: Tiempo Nuevo.</p>
                      <p>1971 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-ledla.htm"><em>La esencia de lo americano</em></a>. Buenos Aires: Pleamar.</p>
                      <p>1971 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-pplc1.htm"><em>Precursores del pensamiento latinoamericano contemporáneo</em></a>. México: Secretaría de Educación Pública.</p>
                      <p>1974 <a target="_blank"  href="file:///A:\zdeylicu.htm"><em>Dependencia y liberación en la cultura latinoamericana</em></a>. México: Joaquín Mortiz.</p>
                      <p>1974 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-pim.htm"><em>Positivism in Mexico</em></a>. Austin: University of Texas Press.</p>
                      <p>1975 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-hdlial.htm"><em>La historia de las ideas en América Latina</em></a>. Tunja: Universidad Pedagógica y Tecnológica de Colombia.</p>
                      <p>1976 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-ddlca.htm"><em>Dialéctica de la conciencia americana</em></a>. México: Alianza Editorial Mexicana.</p>
                      <p>1976 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-pla1.htm"><em>El pensamiento latinoamericano</em></a>. Barcelona: Editorial Ariel (Edición muy aumentada de Dos etapas del pensamiento en Hispanoamérica, 1949).</p>
                      <p>1976 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-fycl1.htm"><em>Filosofía y cultura latinoamericana</em></a>. Caracas: Consejo Nacional de la Cultura. Centro de Estudios Latinoamericanos "Rómulo Gallegos."</p>
                      <p>1976 Filosofía latinoamericana. México: Edicol.</p>
                      <p>1977 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-ltm.htm"><em>Latinoamérica: Tercer Mundo</em></a>. México: Extemporáneos.</p>
                      <p>1978 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-fha.htm"><em>Filosofía de la historia americana</em></a>. México: Fondo de Cultura Económica.</p>
                      <p>1980. <a target="_blank"  href="file:///A:\zbolivar.htm"><em>Simón Bolívar. Integración en la libertad</em></a>. México: Edicol.</p>
                      <p>1981. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-leleh1.htm"><em>Latinoamérica en la encrucijada de la historia</em></a>. México: UNAM.</p>
                      <p>1981 Sentido de la difusión cultural latinoamericana. México: UNAM.</p>
                      <p>1982. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-lanh.htm"><em>Latinoamérica, un nuevo humanismo</em></a>. Tunja, Colombia: Editorial Bolivariana Internacional.</p>
                      <p>1984. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-fdla.htm"><em>Filosofía de lo americano</em></a>. México: Nueva Imagen (estudios publicados en Cuadernos Americanos desde 1942 a 1981).</p>
                      <p>1984 America o constiintá. Bucarest, Rumania: Editura Stiintifica si Enciclopedica (América como conciencia).</p>
                      <p>1985. El positivismo y la circunstancia mexicana. México: Fondo de Cultura Económica / SEP (selección de textos de El positivismo en México, 1943).</p>
                      <p>1986. América Latina como autodescubrimiento. Bogotá: Universidad Central.</p>
                      <p>1986 <em>América Latina en sus ideas</em>, México-UNESCO</p>
                      <p>1987.<strong><a target="_blank"  href="file:///A:\zconverg.htm">Convergencia y especificidad de los valores culturales en América Latina y el Caribe</a></strong>. México: UNAM</p>
                      <p>1988. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-dlmyb.htm"><em>Discurso desde la marginación y la barbarie</em></a>. Barcelona: Anthropos.</p>
                      <p>1988 ¿Por qué América Latina? México: UNAM (Textos de Ciencias Sociales).</p>
                      <p>1989. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-edda.htm"><em>El descubrimiento de América y su sentido actual</em></a>. México: Fondo de Cultura Económica.</p>
                      <p>1990. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-deil.htm"><em>Descubrimiento e identidad latinoamericana</em></a>. México: UNAM.</p>
                      <p>1991. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-qahsp.htm">Quinientos años de historia: sentido y proyección</a>. México: Fondo de Cultura Económica.</p>
                      <p>1991. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-ipda.htm">Ideas y presagios del descubrimiento de América</a>. México: Fondo de Cultura Económica</p>
                      <p>1991. L'Amerique Latine face à l'histoire. Paris: Lierre Caudrier.</p>
                      <p>1992. <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-roah.htm"><em>The Role of The Americas in History</em></a>. Savage (Maryland): Rowman &amp; Littlefield Publishers.</p>
                      <p>1993 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-faldh.htm"><em>Filosofar a la altura del hombre</em></a>. México: UNAM.</p>
                      <p>1993 <a target="_blank"  href="http://ensayo.rom.uga.edu/filosofos/mexico/zea/bibliografia/z-rdlc.htm"><em>Regreso de las carabelas</em></a>. México: UNAM.</p>
                      <div>
                      <ul>
                      <li>
                      <p><em>Fuentes de la cultura latinoamericana. </em> Fondo de Cultura Económica, México. (2 tomos)</p>
                      </li>
                      <li>
                      <p><em>Fin del siglo XX ¿Centuria perdida?</em> Fondo de Cultura Económica, México.</p>
                      </li>
                      <li>
                      <p><em>Fin de milenio, emergencia de los marginados</em>. Fondo de Cultura Económica, México.</p>
                      </li>
                      </ul>
                      </div>


          </div>
        </div>
      </div>
  </section>
